# config/config.yml

exchange:
  id: "kraken"
  api_key: "DaNoXnhwab75ZNClonSrUz4DgybqSJDUKo4AEOQN5sIGxOurJI4uMdEK"
  api_secret: "2xXYSro2i9//lNctUusoVDRWk4/bvOoYW9YekF6xhMHjiauF4coztYyrN58A8G4l+t9ZSBnJcTQiaMM+EjBoxw=="
  test_mode: true  # Set to false for live trading

trading:
  symbol: "BTC/USD"
  lower_price: 82000.0
  upper_price: 92000.0
  grid_quantity: 10
  total_investment: 1000.0
  stop_loss: 80000.0
  trailing_stop:
    enabled: true
    percentage: 0.05  # 5%
  dynamic_grids: true
  strategy:
    type: "default"  # Options: "default", "custom"
    parameters:
      volatility_period: 14
      rsi_threshold: 70
      macd_fast_period: 12
      macd_slow_period: 26
      macd_signal_period: 9

logging:
  level: "INFO"
  file: "logs/bot.log"

performance:
  log_interval: 60 # in seconds